name: sandbox

on:
  push:

jobs:
  debug:
    runs-on: windows-latest

    strategy:
      matrix:
        node:
        - 10
        - 12
        - 14

    name: Node ${{ matrix.node }} sample

    steps:
      - run: echo ${{ github.event_name }}

      - name: Dump
        run: echo ${{ matrix.node }}

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
